name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'

jobs:
  build:
    defaults:
      run:
        working-directory: ./reports
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path:: reports/package-lock.json
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
          ## Add and uncomment any environment variables here
          EVIDENCE_SOURCE__bigquery__authenticator: ${{ secrets.EVIDENCE_SOURCE__bigquery__authenticator }}
          EVIDENCE_SOURCE__bigquery__location: ${{ secrets.EVIDENCE_SOURCE__bigquery__location }}
          EVIDENCE_SOURCE__bigquery__client_email: ${{ secrets.EVIDENCE_SOURCE__bigquery__client_email }}
          EVIDENCE_SOURCE__bigquery__private_key: ${{ secrets.EVIDENCE_SOURCE__bigquery__private_key }}
          EVIDENCE_SOURCE__bigquery__project_id: ${{ secrets.EVIDENCE_SOURCE__bigquery__project_id }}
        run: |
          npm run sources
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './reports/build/${{ github.event.repository.name }}'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
